// The content pipeline: measure the space, publish the campaign, re-verify the product.
//
// Unlike the search-heavy repos in this family, generating a level here costs microseconds
// (a level is nine bits and its par is one array lookup), so the *reason* this file exists
// is not cost. It exists to put a stable id on each campaign level so `#/lot/<id>` can be
// shared, and to leave a checked-in, reviewable record of what was measured:
//
//   * the distance histogram of all 512 positions, and the quantile bands cut from it,
//   * every shipped level's par, re-read from the serialised row and looked up in a
//     freshly built table, so a hand-edit to a number fails the build here and again in
//     `node test/library.test.mjs`.
//
//   node tools/bake.mjs                 # js/data/levels.js
//   PER_BAND=24 node tools/bake.mjs     # longer campaign
//   PROBE=2000 node tools/bake.mjs      # measure the generator's accept rate + timing
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { makeSet, makeLevel, TIERS, tierByKey, census, spreadPars } from '../js/core/make.js';
import { table, buildTable, formula } from '../js/core/solve.js';
import { RINGS, canToggle, bitsOf } from '../js/core/game.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const PER_BAND = Number(process.env.PER_BAND || 16);
const PROBE = Number(process.env.PROBE || 200);

// ---- 1. the space, measured -----------------------------------------------------------
const hist = census();
console.log('table:', JSON.stringify(hist.table));
console.log('bands:', JSON.stringify(hist.bands));
const t = table();
if (!t.complete || !t.isPath) throw new Error('the 512-position sweep is neither complete nor a path');
if (t.dist[(1 << RINGS) - 1] !== formula(RINGS)) throw new Error('closed form disagrees with the search');

// ---- 2. the generator, measured -------------------------------------------------------
const stats = {};
const t0 = Date.now();
for (let i = 0; i < PROBE; i++) {
  for (const tier of TIERS) makeLevel(`probe-${i}`, tier.key, stats);
}
const per = PROBE * TIERS.length;
const ms = (Date.now() - t0) / per;
console.log(`generator: ${per} levels made, accepted ${stats.accepted}/${per} (${((100 * stats.accepted) / per).toFixed(1)}%), ${ms.toFixed(4)} ms/level`);
if (stats.accepted !== per) throw new Error('the generator rejected a level it should always be able to make');

// ---- 3. the campaign, then re-verified from its serialised form ------------------------
const fresh = buildTable(RINGS); // a second, independent table: rows are checked against this
const out = [];
for (const tier of TIERS) {
  const set = makeSet(tier.key, PER_BAND);
  for (const lv of set) {
    const row = {
      id: `${tier.key}-${String(out.filter((o) => o.tier === tier.key).length + 1).padStart(2, '0')}`,
      tier: tier.key,
      n: lv.n,
      state: lv.state,
      par: lv.par,
      rings: bitsOf(lv.state, lv.n).reduce((a, b) => a + b, 0),
      movable: Array.from({ length: lv.n }, (_, k) => k).filter((k) => canToggle(lv.state, k, lv.n)).length,
    };
    if (fresh.dist[row.state] !== row.par) {
      throw new Error(`${row.id}: claims par ${row.par}, the table says ${fresh.dist[row.state]}`);
    }
    if (row.par < tier.min || row.par > tier.max) {
      throw new Error(`${row.id} par ${row.par} outside measured band ${tier.min}-${tier.max}`);
    }
    out.push(row);
  }
}

// Bands as *shipped*: the min/max of the levels that actually made it in, which is the
// number the UI prints. The generation envelope they were drawn from is recorded next to it
// so the two are never silently conflated.
const meta = TIERS.map((tier) => {
  const mine = out.filter((l) => l.tier === tier.key).map((l) => l.par);
  const lo = Math.min(...mine);
  const hi = Math.max(...mine);
  return {
    key: tier.key, label: tier.label, min: lo, max: hi,
    envelope: [tier.min, tier.max],
    states: tier.states,
    levels: mine.length,
    blurb: `${lo}-${hi} 步`,
  };
});

// The histogram the bands were cut from, kept small and printable: the distances are 0..511
// exactly once each on a path graph, so `flat` plus min/max carries the whole claim.
const counts = new Map();
for (let s = 0; s < fresh.size; s++) counts.set(fresh.dist[s], (counts.get(fresh.dist[s]) || 0) + 1);
const histogram = {
  nodes: fresh.size,
  distinctDistances: counts.size,
  maxCount: Math.max(...counts.values()),
  maxDist: fresh.maxDist,
  atState: fresh.argMaxDist,
  flat: Math.max(...counts.values()) === 1,
  allOnDist: fresh.dist[fresh.size - 1],
  closedForm: formula(RINGS),
  cuts: TIERS.map((x) => ({ key: x.key, min: x.min, max: x.max, states: x.states })),
};

const lines = [
  '// Generated by tools/bake.mjs — the levels in this game are measurements, not opinions.',
  '// `par` is the exhaustive BFS distance (in single-ring moves) from `state` to the',
  '// cleared sword, and the bands in TIERS_META are quantiles of HISTOGRAM, which is the',
  '// measured distance histogram of all 512 positions. Re-run `node tools/bake.mjs`',
  '// instead of hand-editing; `node test/library.test.mjs` re-derives every number here',
  '// from js/core/solve.js and fails if a row and its par ever disagree.',
  `export const HISTOGRAM = ${JSON.stringify(histogram)};`,
  `export const TIERS_META = ${JSON.stringify(meta)};`,
  'export const LEVELS = [',
  ...out.map((l) => `  ${JSON.stringify(l)},`),
  '];',
  '',
];
const path = join(root, 'js', 'data', 'levels.js');
mkdirSync(dirname(path), { recursive: true });
writeFileSync(path, lines.join('\n'));

const byTier = {};
for (const l of out) byTier[l.tier] = (byTier[l.tier] || 0) + 1;
console.log(`wrote ${out.length} levels (${Object.entries(byTier).map(([k, n]) => `${k}:${n}`).join(' ')}) -> js/data/levels.js`);
console.log(`spread check: ${TIERS.map((x) => `${x.key}=${spreadPars(x, PER_BAND).length}`).join(' ')}`);
console.log(`bands shipped: ${meta.map((m) => `${m.key} ${m.min}-${m.max}`).join(' | ')}`);
console.log(`histogram: ${JSON.stringify(histogram)}`);
